### ISSUE TITLE
Tag and add to packagist

### ISSUE THREAD

**Issue by deviantintegral** [Capgemini/drupal-doctrine-cache#1]
I'm looking to rely on this for <a href="https://www.drupal.org/project/amazons3">amazons3</a> module. However, only having a master branch will lead to problems for anyone not wanting to install dev packages. We'll also need to manually add the repo to composer.json, since the repository name doesn't match the repository name.

Any chance this can be tagged and packaged up?

**Comment by deviantintegral** [comment]
For anyone else, I've put up a tag in my fork. You still have to add the repositories line, but at least it will prevent pulling in dev branches in other projects.

https://github.com/deviantintegral/drupal-doctrine-cache/releases/tag/0.1

**Comment by tsphethean** [comment]
I've tagged v0.0.1(https://github.com/Capgemini/drupal-doctrine-cache/releases/tag/0.0.1) - the library is already on packagist at https://packagist.org/packages/capgemini/drupal_doctrine_cache

**Comment by tsphethean** [comment]
And the tag is now pushed to packagist - thanks @deviantintegral
